# NumPy Library in Python

## Introduction to NumPy
NumPy (Numerical Python) is a Python library designed for numerical operations, widely used in data analytics and data science.  
It provides efficient handling of numerical and multi-dimensional arrays with smaller memory consumption and faster runtime compared to Python lists or loops.

### Why Use NumPy?
- **Speed**: NumPy arrays (ndarrays) are up to 50x faster than Python lists.
- **Memory Efficiency**: Uses less memory than lists.
- **Functionality**: Offers a wide range of mathematical and array manipulation functions.
- **Big Data**: Ideal for large datasets in analytics.

### Installation
```bash
pip install numpy
```
If already installed, you’ll see:
```
Requirement already satisfied: numpy in c:\users\user\anaconda3\lib\site-packages (1.19.5)
```
### Importing NumPy
```python
import numpy as np
```

## 1. Creating NumPy Arrays

In [22]:
### Basic Array Creation

import numpy as np

# Creating a Python list
list_a = [1, 2, 3]
print(list_a)
print("Type of list_a:", type(list_a))
print("Length:", len(list_a))
print("Max:", max(list_a))
print("Min:", min(list_a))

# Creating a NumPy array
a = np.array([1, 2, 3])
print(a)
print("Type of a:", type(a))


[1, 2, 3]
Type of list_a: <class 'list'>
Length: 3
Max: 3
Min: 1
[1 2 3]
Type of a: <class 'numpy.ndarray'>


In [18]:
### Specifying Data Type
# Float array
a_float = np.array([1, 2, 3], dtype=float)
print(a_float)

# String array
a_str = np.array([1, 2, 3], dtype=str)
print(a_str)
print("Last element:", a_str[-1])


[1. 2. 3.]
['1' '2' '3']
Last element: 3


In [27]:
### Multi-Dimensional Arrays
# 2D array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print("Dimensions:", b.ndim)
print("Element at b[1,1]:", b[1, 1])

# 4D array
d = np.array([[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]])
print("Dimensions:", d.ndim)

[[1 2 3]
 [4 5 6]]
Dimensions: 2
Element at b[1,1]: 5
Dimensions: 4


In [30]:
### Array Shape and Type
print("Shape:", b.shape)
print("Data type:", a_float.dtype)


Shape: (2, 3)
Data type: float64


In [ ]:
## 2. Accessing and Modifying Array Elements

### Accessing Elements
a = np.array([1, 2, 3, 4, 5, 6])
print(a[2])         # Element at index 2
print(a[0:2])       # First two elements
print(a[4:])        # From index 4 to end

3
[1 2]
[5 6]


In [43]:
### Accessing Rows and Columns

a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print("First row:", a[0, :])
print("Last column:", a[:, 6])
print("Third column:", a[:, 2])


First row: [1 2 3 4 5 6 7]
Last column: [ 7 14]
Third column: [ 3 10]


In [44]:
### Modifying Elements

a[0, 3] = 40
a[0, 4] = 50
print("Modified array:\n", a)


Modified array:
 [[ 1  2  3 40 50  6  7]
 [ 8  9 10 11 12 13 14]]


In [52]:
## 3. Special Array Creation Methods

### Zeros and Ones
print(np.zeros((3, 3)))
print(np.ones((3, 3), dtype=int))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [53]:
### Full Array

vara = 20
print(np.full((3, 3), vara, dtype=int))

[[20 20 20]
 [20 20 20]
 [20 20 20]]


In [281]:
### Random Arrays

print(np.random.rand(3, 3))           # Random floats
print(np.random.randint(1, 10, (3,3))) # Random integers

[[0.32223158 0.70015083 0.02078132]
 [0.89958572 0.87762716 0.41878817]
 [0.48612918 0.40872148 0.49671208]]
[[5 4 7]
 [7 2 7]
 [1 8 1]]


In [436]:
### Identity Matrix
print(np.identity(3, dtype=int))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [452]:
## 4. Arithmetic Operations

### Basic Arithmetic

a = np.array([1, 2, 3, 4])
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)
print(a // 2)
print(a ** 3)

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[0 1 1 2]
[ 1  8 27 64]


In [453]:
### Statistical Operations

print("Min:", np.min(a))
print("Max:", np.max(a))
print("Mean:", np.mean(a))
print("Sum:", np.sum(a))

Min: 1
Max: 4
Mean: 2.5
Sum: 10


In [454]:
### Axis-Based Operations

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("Max per column:", np.max(a, axis=0))
print("Sum per row:", np.sum(a, axis=1))

Max per column: [5 6 7 8]
Sum per row: [10 26]


In [463]:
## 5. Practice Questions

### Question 1: Extract First Three Rows of Last Five Columns

a = np.array([[1,2,3,4,5,6],[10,20,30,40,50,60],[12,12,12,12,12,12],[11,21,31,41,51,61],[13,24,34,44,54,64]])
print(a[:3, 1:])

[[ 2  3  4  5  6]
 [20 30 40 50 60]
 [12 12 12 12 12]]


In [469]:
### Question 2: Extract Last Three Rows of First Five Columns
print(a[2:, :5])

[[12 12 12 12 12]
 [11 21 31 41 51]
 [13 24 34 44 54]]


In [485]:
### Question 3: Create a Plus-Shaped Array

n = 5
z = np.zeros((n, n), dtype=int)
z[n//2, :] = 1
z[:, n//2] = 1
print(z)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


## Summary
- **NumPy Arrays**: Efficient for numerical computations.
- **Accessing/Modifying**: Use slicing and indexing.
- **Special Arrays**: zeros, ones, full, random, identity.
- **Arithmetic**: Element-wise math and statistical ops.
- **Applications**: Essential for data science due to speed, memory efficiency, and flexibility.